/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLySanPhamNgoaiQuay extends javax.swing.JPanel {

    final String header[] = {"Mã sản phẩm", "Ngày sản xuất", "Hạn sử dụng", "Mã cửa hàng", "Giá", "Giảm giá (%)", "Số lượng"};
    final DefaultTableModel tb = new DefaultTableModel(header,0);
    Connect cn = new Connect();
    Connection conn = null;
    ResultSet rs;
    public QuanLySanPhamNgoaiQuay() {
        initComponents();
        loadBang();
    }
  
    public void loadBang(){
        try {
            conn = cn.getConnectDB();
            int number;
            Vector row;
            String sql = "select * from sales.stocks";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ResultSetMetaData metaData = rs.getMetaData();
            number = metaData.getColumnCount();
            tb.setRowCount(0);
             while (rs.next()) {
                row = new Vector();
                for (int i = 1; i <= number; i++) {
                    row.addElement(rs.getString(i));
                }
                tb.addRow(row);
                tbl_sanPhamBan.setModel(tb);
            }
             
            st.close();
            rs.close();
            conn.close();
        } catch (Exception e) {
        }
        tbl_sanPhamBan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if(tbl_sanPhamBan.getSelectedRow() >= 0){
                    txt_productID.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 0)+ "");
                    txt_ngaySX.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 1)+ "");
                    txt_hanSD.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 2)+ "");
                    txt_maCuaHang.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 3)+ "");
                    txt_gia.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 4)+ "");
                    txt_giamGia.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 5)+ "");
                    txt_soLuong.setText(tbl_sanPhamBan.getValueAt(tbl_sanPhamBan.getSelectedRow(), 6)+ "");   
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void Reset(){
        txt_gia.setText("");
        txt_giamGia.setText("");
        txt_hanSD.setText("");
        txt_maCuaHang.setText("");
        txt_ngaySX.setText("");
        txt_productID.setText("");
        txt_soLuong.setText("");
        loadBang();
        txt_productID.setEnabled(true);
        txt_hanSD.setEnabled(true);
        txt_ngaySX.setEnabled(true);
        txt_maCuaHang.setEnabled(true);
        btn_them.setEnabled(true);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_productID = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        txt_giamGia = new javax.swing.JTextField();
        txt_soLuong = new javax.swing.JTextField();
        txt_maCuaHang = new javax.swing.JTextField();
        txt_ngaySX = new javax.swing.JTextField();
        txt_hanSD = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanPhamBan = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1920, 1020));

        jLabel1.setText("Mã sản phẩm");

        jLabel2.setText("Ngày sản xuất");

        jLabel3.setText("Hạn sử dụng");

        jLabel4.setText("Mã cửa hàng");

        jLabel5.setText("Giá");

        jLabel6.setText("Giảm giá (%)");

        jLabel7.setText("Số lượng");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        jButton4.setText("Thoát");

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jButton6.setText("Tìm kiếm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Mã cửa hàng", "Giảm Giá", "Ngày sản xuất", "Hạn sử dụng" }));

        tbl_sanPhamBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sanPhamBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanPhamBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sanPhamBan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(txt_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ngaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hanSD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_giamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_them)
                            .addComponent(btn_reset))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_sua)
                            .addComponent(btn_xoa)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_maCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(561, 561, 561))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_productID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hanSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_them)
                            .addComponent(btn_xoa)
                            .addComponent(jLabel6)
                            .addComponent(txt_giamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngaySX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sua)
                            .addComponent(btn_reset))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_maCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        conn = cn.getConnectDB();
        try {
            if(txt_productID.getText().equals("") || txt_ngaySX.getText().equals("") ||txt_hanSD.getText().equals("") ||txt_maCuaHang.getText().equals("") ||txt_gia.getText().equals("") ||txt_giamGia.getText().equals("") ||txt_soLuong.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            else {
                StringBuffer sb = new StringBuffer();
                String sql_check_pk = "Select product_id, created_at, good_till, store_id from sales.stocks " +
                                        " where product_id = '"+txt_productID.getText()+"' and created_at = '"+txt_ngaySX.getText()+"' and good_till = '"+txt_hanSD.getText()+"' and store_id = '"+txt_maCuaHang.getText()+"'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql_check_pk);
                if(rs.next()){
                    sb.append("Hãy kiểm tra lại mã sản phẩm, mã cửa hàng, ngày sản xuất và hạn sử dụng");
                }
                if(sb.length() > 0){
                    JOptionPane.showMessageDialog(this, sb.toString());
                } else {
                    String sql = "Insert into sales.stocks values("+txt_productID.getText()+", '"+txt_ngaySX.getText()+"', '"+
                            txt_hanSD.getText()+"', "+txt_maCuaHang.getText()+", "+txt_gia.getText()+", "+
                            txt_giamGia.getText()+", "+txt_soLuong.getText()+");" ;
                    System.out.println(txt_ngaySX.getText());
                    st = conn.createStatement();
                    int kq = st.executeUpdate(sql);
                    if(kq > 0) {
                        JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                        Reset();
                    }
                }
                st.close();
            }
            conn.close();
            rs.close();
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_sanPhamBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanPhamBanMouseClicked
        // TODO add your handling code here
        int x = tbl_sanPhamBan.getSelectedRow();
        if(x >= 0) {
            txt_productID.setText(tbl_sanPhamBan.getValueAt(x, 0)+ "");
            txt_ngaySX.setText(tbl_sanPhamBan.getValueAt(x, 1)+ "");
            txt_hanSD.setText(tbl_sanPhamBan.getValueAt(x, 2)+ "");
            txt_maCuaHang.setText(tbl_sanPhamBan.getValueAt(x, 3)+ "");
            txt_gia.setText(tbl_sanPhamBan.getValueAt(x, 4)+ "");
            txt_giamGia.setText(tbl_sanPhamBan.getValueAt(x, 5)+ "");
            txt_soLuong.setText(tbl_sanPhamBan.getValueAt(x, 6)+ "");
            txt_productID.setEnabled(false);
            txt_hanSD.setEnabled(false);
            txt_ngaySX.setEnabled(false);
            txt_maCuaHang.setEnabled(false);
            btn_them.setEnabled(false);
        }
    }//GEN-LAST:event_tbl_sanPhamBanMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        conn = cn.getConnectDB();
        try {
            if(txt_gia.getText().equals("") ||txt_giamGia.getText().equals("") ||txt_soLuong.getText().equals(""))
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            else {
                Statement st = conn.createStatement();
                String sql = "Update sales.stocks set price =  '"+txt_gia.getText()+"' , discount = '"+txt_giamGia.getText()
                        +"' , quantity =  '"+txt_soLuong.getText() +"'  where product_id =  '"+txt_productID.getText()+"'  and created_at = '"+txt_ngaySX.getText()
                        +"' and good_till = '"+txt_hanSD.getText()+"' and store_id =  '"+txt_maCuaHang.getText()+"'  ";
                System.out.println(txt_ngaySX.getText());
                st = conn.createStatement();
                int kq = st.executeUpdate(sql);
                if(kq > 0) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    Reset();
                } else {
                    System.out.println(sql);
                    System.out.println("Koo thực hiện được câu lệnh sql");
                } 
                    
                st.close();
            }
            conn.close();
            rs.close();
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        conn = cn.getConnectDB();
        try {
            String sql = "Delete from sales.stocks where product_id =  '"+txt_productID.getText()+"' and created_at = '"+txt_ngaySX.getText()+"' and good_till = '"+txt_hanSD.getText()+"' and store_id = '"+txt_maCuaHang.getText()+"'" ;
            Statement st = conn.createStatement();
            int chk = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa không?", "Thông báo!", JOptionPane.YES_NO_OPTION );
            if(chk == JOptionPane.YES_OPTION){
                System.out.println(sql);
                st.executeUpdate(sql);
                Reset();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không xóa được!");
        }
        
    }//GEN-LAST:event_btn_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sanPhamBan;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_giamGia;
    private javax.swing.JTextField txt_hanSD;
    private javax.swing.JTextField txt_maCuaHang;
    private javax.swing.JTextField txt_ngaySX;
    private javax.swing.JTextField txt_productID;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_soLuong;
    // End of variables declaration//GEN-END:variables
}
